apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: terraform
          image: terraform-k8s:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          # Add any other environment variables your terraform scripts need
      restartPolicy: Never
