apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
spec:
  template:
    spec:
      containers:
        - name: terraform
          image: sidwas1998/terraform-k8s:latest
          command: ["/bin/sh", "-c", "./run-terraform.sh"]   # run your wrapper
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_DEFAULT_REGION
      restartPolicy: Never

